#include<bits/stdc++.h>
#define fast_io ios_base::sync_with_stdio(false);cin.tie(NULL)
#define read(n) int n;cin>>n
#define Read(n,m) int n,m;cin>>n>>m
#define loop(x,n) for(int x = 0; x < n; ++x)
#define vec vector<int>
#define vec2d vector<vector<int>>
using namespace std;
void init_code() {
fast_io;
#ifndef ONLINE_JUDGE
freopen("input.txt", "r", stdin);
freopen("output.txt", "w", stdout);
#endif // ONLINE_JUDGE
}
char solve(string s,string t){
	vector<int> v(256,0);
	for(int i=0;i<s.size();i++){
		v[s[i]-'a']++;
	}
    for(int i=0;i<t.size();i++){
		v[t[i]-'a']--;
	}
	for(int i=0;i<v.size();i++){
		if(v[i]<0)
			return (i+'a');
	}
}
int main(){
	init_code();
	string s,t;
	cin>>s>>t;
	cout<<solve(s,t);


	
}
/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.*/